name: Commitlint
on:
  push:
    branches-ignore:
      - master

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.head_ref }}
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: |
          echo "::set-env name=node-version::$(cat ./.nvmrc)"

      - name: Setup Node.js v${{ env.node-version }}
        uses: actions/setup-node@v1.3.0
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        run: |
          npm install -g @commitlint/cli
          npm install \
            lerna \
            @commitlint/{config-conventional,config-lerna-scopes}

      - name: Validate commit messages
        run: |
          IFS=$'\n'
          messages=($(node -p << EOF
            ${{ toJson(github.event.commits.*.message) }}.join('\n');
          EOF))
          unset IFS

          echo "linting ${#messages[@]} commits"

          for msg in "${messages[@]}"
          do
            echo "  • ${msg}"
            echo "${msg}" | commitlint
          done
