name: Commitlint
on:
  push:
    branches-ignore:
      - master

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - name: Count commits
        run: |
          echo "::set-env name=commit-count::$(node -p '${{ toJson(github.event.commits.*.id) }}.length')"

      - name: Checkout ${{ github.head_ref }}
        uses: actions/checkout@v1.2.0
        with:
          fetch-depth: ${{ env.commit-count }}

      - name: Read .nvmrc
        run: |
          echo "::set-env name=node-version::$(cat ./.nvmrc)"

      - name: Setup Node.js v${{ env.node-version }}
        uses: actions/setup-node@v1.3.0
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        run: |
          npm install -g @commitlint/cli
          npm install \
            lerna \
            @commitlint/{config-conventional,config-lerna-scopes}

      - name: Validate commit messages
        run: |
          commitlint \
            --from ${{ github.event.before }} \
            --to ${{ github.event.after }}
