name: PR Labeler
on:
  pull_request:
    branches:
      - master

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
    
