name: Packages

on:
  pull_request:
    paths:
      - 'packages/**'
    branches:
      - master
    types: [opened,synchronize,reopened,labeled]

env:
  scope: '@astolat'
  registry-url: 'https://registry.npmjs.org/'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    if: github.event.action != 'labeled'
    steps:
      - name: Checkout ${{ github.head_ref }}
        uses: actions/checkout@v1.2.0

      - name: Read .nvmrc
        run: |
          echo "::set-env name=node-version::$(cat ./.nvmrc)"

      - name: Setup Node.js v${{ env.node-version }}
        uses: actions/setup-node@v1.3.0
        with:
          node-version: ${{ env.node-version }}
          scope: ${{ env.scope }}
          registry-url: ${{ env.registry-url }}

      - name: Set variables
        run: |
          echo "::set-env name=yarn-cache::$(yarn cache dir)"

      - name: Restore yarn cache
        id: cache
        uses: actions/cache@v1.0.3
        with:
          path: ${{ env.yarn-cache }}
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

  check:
    name: Check
    runs-on: ubuntu-latest
    needs: [setup]
    if: github.event.action != 'labeled'
    strategy:
      fail-fast: false
      matrix:
        command: [lint,test,check]
    steps:
      - name: Checkout ${{ github.head_ref }}
        uses: actions/checkout@v1.2.0

      - name: Read .nvmrc
        run: |
          echo "::set-env name=node-version::$(cat ./.nvmrc)"

      - name: Setup Node.js v${{ env.node-version }}
        uses: actions/setup-node@v1.3.0
        with:
          node-version: ${{ env.node-version }}
          scope: ${{ env.scope }}
          registry-url: ${{ env.registry-url }}

      - name: Set variables
        run: |
          echo "::set-env name=yarn-cache::$(yarn cache dir)"
          echo "::add-path::$(yarn global bin)"

      - name: Restore yarn cache
        uses: actions/cache@v1.0.3
        with:
          path: ${{ env.yarn-cache }}
          key: yarn-cache-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: |
          yarn

      - name: Run ${{ matrix.command }} for changed packages
        run: |
          CMD='${{ matrix.command }}'
          ARGS=`git diff --name-only --diff-filter=ACMR origin/${{ github.base_ref }} -- '***.[jt]s' '***.[jt]sx'`
          COUNT=`echo ${ARGS} | wc -l`

          [[ "${COUNT}" == "0" ]] && exit 0

          case ${CMD} in
            lint)
              CMD='eslint'
              ARGS=${ARGS}
              ;;
            test)
              ARGS='--changedSince origin/${{ github.base_ref }}'
              ;;
            check)
              echo `node -p "JSON.stringify({ ...require('./tsconfig.json'), files: process.argv[1].split(/[\r\n]+/g) })" "${ARGS}"` > ./tsconfig.json
              ARGS=''
              ;;
          esac

          yarn ${CMD} ${ARGS}

          git checkout -- ./tsconfig.json


  prerelease:
    name: Pre-Release
    runs-on: ubuntu-latest
    if: github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'prerelease')
    steps:
      - name: Checkout ${{ github.head_ref }}
        uses: actions/checkout@v1.2.0

      - name: Read .nvmrc
        run: |
          echo "::set-env name=node-version::$(cat ./.nvmrc)"

      - name: Setup Node.js v${{ env.node-version }}
        uses: actions/setup-node@v1.3.0
        with:
          node-version: ${{ env.node-version }}
          scope: ${{ env.scope }}
          registry-url: ${{ env.registry-url }}

      - name: Set variables
        run: |
          echo "::set-env name=yarn-cache::$(yarn cache dir)"
          echo "::add-path::$(yarn global bin)"

      - name: Restore yarn cache
        uses: actions/cache@v1.0.3
        with:
          path: ${{ env.yarn-cache }}
          key: yarn-cache-${{ hashFiles('yarn.lock') }}

      - name: Install global dependencies
        run: |
          yarn global add lerna

      - name: Bootstrap
        run: |
          lerna bootstrap \
            --since origin/${{ github.base_ref }}

      - name: Publish (pr${{ github.event.pull_request.number }})
        env:
          CI: true
          NODE_ENV: production
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          lerna publish \
            --conventional-prerelease \
            --no-changelog \
            --canary \
            --preid prerelease \
            --dist-tag 'pr${{ github.event.pull_request.number }}' \
            --no-verify-access \
            --amend \
            --yes
