name: Release
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout ${{ github.base_ref }}
        uses: actions/checkout@v2-beta
        with:
          ref: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read .nvmrc
        run: |
          echo "::set-env name=node-version::$(cat ./.nvmrc)"

      - name: Setup Node.js v${{ env.node-version }}
        uses: actions/setup-node@v1.3.0
        with:
          node-version: ${{ env.node-version }}
          scope: ${{ env.scope }}
          registry-url: ${{ env.registry-url }}

      - name: Set variables
        run: |
          echo "::set-env name=yarn-cache::$(yarn cache dir)"
          echo "::add-path::$(pwd)/node_modules/.bin"

          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout -B ${{ github.base_ref }}

      - name: Restore yarn cache
        uses: actions/cache@v1.0.3
        with:
          path: ${{ env.yarn-cache }}
          key: yarn-cache-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: |
          yarn install

      - name: Publish (latest)
        env:
          CI: true
          NODE_ENV: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          lerna publish \
            --no-verify-access \
            --create-release github \
            --message 'chore(release): published' \
            --changelog-preset conventionalcommits \
            --yes
